<h2>Dr. Vetéssy Géza (1908-1945)</h2>
<h3>Nehéz időkben szeretettel szolgáló tanár és cserkészvezető</h3>
<p>Nehéz idők jártak az 1930-1940-es években a tanítással-neveléssel foglalkozók számára is. Az egyik újságban 1934-ben ilyen sor olvasható: „Ezer név - ezer állás". Tehát ennyi állástalan pedagógus várt elhelyezkedésre. Nagy esemény volt, ha egy tanár állást vállalhatott. Erre vágyott Vetéssy Géza, akit az alábbiakban ismertetünk meg az ICHTHÜSZ újság olvasóival.</p>
<h3>Debrecentől - Kecskemétig</h3>
<p>Vetéssy Géza Debrecenben született 1908-ban. Iskoláit mindvégig a református elemi, gimnázium és egyetem fokozatain végezte. Az érettségit 1927-ben jeles eredménnyel tette le. Az egyetemen magyar-latin szakon tanult ösztöndíjasként. Ilyen módon alkalma volt külföldi utakat is megjárni - Görögországban, Rómában, Ausztriában - és ezzel nyelvismeretét is gyarapította, látókörét szélesítette, mélyítette. A Kollégium Tanárképző Főiskoláján is tanult. Amikor 1932-ben diplomáját megszerezte, taníthatott a gimnázium gyakorló iskolájában is, mint állástalan tanár. Helyettes tanár is volt egy ideig a Kollégium Gimnáziumában. Tudomására jutott, hogy a Kecskeméti Református Gimnázium magyar-latin szakos tanárt keres. Jelentkezett, és miután próbatanítása mindkét szakból kitűnően sikerül, 1934 októberétől szolgálatba állhatott.</p>
<h3>Tanári és cserkész-szolgálata</h3>
<p>Debrecenből magával hozta a hit és szeretet ajándékát és kötelezettségét és ezt a kecskeméti hasonló légkörben meg is valósíthatta. Rokonszenves egyénisége, komoly pedagógiai felkészültsége rövid időn belül megmutatkozott. Mindjárt az elején megállapította, hogy kiknek nincsen könyvük. A szegény gyerekek megkapták ingyen. Megtanította osztályaiban az olvasmány elemzés alapelemeit.</p>
<p>Rövidesen ő lett az önképzőkör tanár-elnöke. Külön csoportokat hozott létre irodalmi, néprajzi és művészi érdeklődésűeknek. Így rövid időn belül az önképzőkör lett az iskola legelevenebb tanulói közössége. Nem csoda, hogy előbb a kecskeméti középiskolák, majd a Tankerületi Főigazgatóság a Pest-megyei iskolák szakfelügyelőjévé nevezte ki. Az iskola szülői munkaközösségében is egymásután tartotta előadásait. Közben megszerezte doktorátusát. Dolgozatának címe: Az antik eposzi elemek Vörösmarty Mihály kisebb eposzaiban. Ez a mun­kája nyomtatásban is megjelent.</p>
<p>Tanári működésével egyidejűleg a cserkészcsapatban is vállalta a szolgálatot úgy, hogy a helyi csapat parancsnoksága után nem sokkal a Kecskeméti Kerület vezetését is rábízták. Szabadkán az ő előadásával alakult meg az öregcserkészek csoportja. Cserkészeivel számos gyalog és kerékpártúrát vezetett. Egy nyári tábor azért nem valósulhatott meg, mert őt katonai szolgálatra behívták. A helyi és kerületi csapatokban szorgalmazta és vezette a képzéseket.</p>
<p>Ilyen szorgalmas tevékenysége közben - ahogyan a rá emlékezők írják - gyökeres kecskeméti lett. Ezt előmozdította az is, hogy egy régi kecskeméti családból, a gyülekezetnek főgondnokokat adó Szabó családból választott feleséget. Három kislánya tapasztalhatta meg édesapai gondosságát, őszinte szeretetét.</p>
<h3>Közéleti tevékenysége</h3>
<p>Kecskeméten alakult meg a Dunamelléki Református Egyházkerület első népfőiskolája 1942-ben. Ő vállalta az irodalmi előadásokat, és 36 író bemutatását tervezte. De előadásokat tartott a népfőiskolának helyet adó KIE-ben is. Ilyen előadása volt a Kalevala bemutatása. Tanulóival és a cserkészekkel a tanyai kiszállásokon is vállalta nemcsak a vezetést, de az előadásokat is. Például a Talfája nevű tanyai központban a gályarabokról tartott előadást, máshol a Reformációról. Így élénk kapcsolata alakult ki magával a tanyák egyszerű népével is.</p>
<p>Igen jelentős volt a város legtekintélyesebb társaságában, a Katona József Társaságban való ténykedése. Ő ismertette az elfelejtett kecskeméti költő, Mátyásy József életét és költészetét. Az ő közreműködésével létesült emléktábla a költő emlékére. Az ünnepségen ő mondta az ünnepi beszédet. Ez a műve nyomatásban is megjelent. Tanulmányai jelentek meg a Protestáns Tanügyi Szemlében, így Debrecenben is közölték írásait. 1942-ben - amikor a kecskeméti egyház tu­lajdonában volt a Részvény nyomda - jelenhetett meg egyik jelentős irodalmi munkája: A magyar írók Széchenyi eszméinek szolgálatában címmel. Több előadásban foglalkozott az erdélyi írókkal mind tanítványai körében, mind a Katona József Társaságban és a helyi folyóiratban, a Hajnalodikban is. Szinte nem lehet felsorolni tevékeny szolgálatainak sorát, de az eddigiek is mutatják, hogy valóban a tanítás-nevelés és a magyar haza szolgálatában használta Istentől kapott tehetségét. A kapott tehetséget egyben feladatnak is tekintette.</p>
<p>Ezt a rendkívül gazdag és áldozatos életet kívánta áldozatul az az áldatlan és értelmetlen háború, amely előbb csak rövid időre, majd harctéri szolgálatra hívta be. Hadifogságba került és 1945. január 29-én tífuszban elhunyt. Halála előtt bajtársainak átadta jegygyűrűjét azzal, hogy szeretteinek juttassák haza. Bajtársai ezt teljesítették is. Egyik bajtársa Vésztőről Vetéssy Géza feleségének édesapját értesítette csendes elhunytáról és végrendelkezéséről. Kecskeméten gyászjelentések adták tudtul a hírt azzal a bibliai üzenettel, ami Dániel 12,3-ban olvasható: „Akik sokakat az igazságra visznek fénylenek, miként a csillagok, örökkön-örökké„.</p>
<p>Vetéssy Géza emléke tovább é1 Kecskeméten és adja Isten, hogy sokakban az országban is így legyen. Előbb a család és volt tanítványai emléktáblát adtak neki, majd pedig amikor újra az egyház tulajdonába került az az iskola, ahol ő csak egy évtizedig szolgálhatott és cserkészcsapata is megalakulhatott, felvette a nevét. Vagyis Kecskeméten a 121-es cserkészcsapat viszi tovább dr. Vetéssy Gézának - bizonyára nemcsak nevét - de tartalmas életének szolgálatait is.</p>
<p>Dr. Vetéssy Gézának már tanári működése kibontakozása idején a fenntartó testület tagjai arról tanácskoztak, hogy mikor igazgató változásra kerül sor, akkor csak az ő személye kerülhet első helyre. Fájdalom, erre nem kerülhetett sor, az ő elmúlta miatt. De Isten útjai milyen különösek, amikor e sorok megjelenhetnek, akkor az általa szeretettel szolgált Kecskeméti Református Gimnázium igazgatója az ő egyik leánya: Vetéssy Katalin.</p>
<p>Isten áldja és őrizze ebben a szolgáltában és adjon neki hitet, szeretetet felülről való bölcsességgel együtt!</p>